FROM debian:jessie
MAINTAINER Dennis de Greef <github@link0.net>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	apt-utils \
	less \
	man \
	net-tools \
	telnet

